# Generated by Django 5.0.14 on 2026-01-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
